<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // Insert default languages
        DB::table('langs')->insert([
            ['name' => 'ABAP', 'ace_mode' => 'abap', 'logo' => ''],
            ['name' => 'ABC', 'ace_mode' => 'abc', 'logo' => ''],
            ['name' => 'ActionScript', 'ace_mode' => 'actionscript', 'logo' => ''],
            ['name' => 'ADA', 'ace_mode' => 'ada', 'logo' => ''],
            ['name' => 'Alda', 'ace_mode' => 'alda', 'logo' => ''],
            ['name' => 'Apache Conf', 'ace_mode' => 'apache_conf', 'logo' => ''],
            ['name' => 'Apex', 'ace_mode' => 'apex', 'logo' => ''],
            ['name' => 'AQL', 'ace_mode' => 'aql', 'logo' => ''],
            ['name' => 'AsciiDoc', 'ace_mode' => 'asciidoc', 'logo' => ''],
            ['name' => 'ASL', 'ace_mode' => 'asl', 'logo' => ''],
            ['name' => 'Assembly ARM32', 'ace_mode' => 'assembly_arm32', 'logo' => ''],
            ['name' => 'Assembly x86', 'ace_mode' => 'assembly_x86', 'logo' => ''],
            ['name' => 'Astro', 'ace_mode' => 'astro', 'logo' => ''],
            ['name' => 'AutoHotkey / AutoIt', 'ace_mode' => 'autohotkey', 'logo' => ''],
            ['name' => 'BatchFile', 'ace_mode' => 'batchfile', 'logo' => ''],
            ['name' => 'BibTeX', 'ace_mode' => 'bibtex', 'logo' => ''],
            ['name' => 'C', 'ace_mode' => 'c_cpp', 'logo' => ''],
            ['name' => 'C++', 'ace_mode' => 'c_cpp', 'logo' => ''],
            ['name' => 'C9Search', 'ace_mode' => 'c9search', 'logo' => ''],
            ['name' => 'Cirru', 'ace_mode' => 'cirru', 'logo' => ''],
            ['name' => 'Clojure', 'ace_mode' => 'clojure', 'logo' => ''],
            ['name' => 'Cobol', 'ace_mode' => 'cobol', 'logo' => ''],
            ['name' => 'CoffeeScript', 'ace_mode' => 'coffee', 'logo' => ''],
            ['name' => 'ColdFusion', 'ace_mode' => 'coldfusion', 'logo' => ''],
            ['name' => 'Crystal', 'ace_mode' => 'crystal', 'logo' => ''],
            ['name' => 'C#', 'ace_mode' => 'csharp', 'logo' => 'https://img.icons8.com/nolan/50/c-sharp-logo.png'],
            ['name' => 'Csound Document', 'ace_mode' => 'csound_document', 'logo' => ''],
            ['name' => 'Csound', 'ace_mode' => 'csound_orchestra', 'logo' => ''],
            ['name' => 'Csound Score', 'ace_mode' => 'csound_score', 'logo' => ''],
            ['name' => 'CSS', 'ace_mode' => 'css', 'logo' => ''],
            ['name' => 'Curly', 'ace_mode' => 'curly', 'logo' => ''],
            ['name' => 'Cuttlefish', 'ace_mode' => 'cuttlefish', 'logo' => ''],
            ['name' => 'D', 'ace_mode' => 'd', 'logo' => ''],
            ['name' => 'Dart', 'ace_mode' => 'dart', 'logo' => ''],
            ['name' => 'Diff', 'ace_mode' => 'diff', 'logo' => ''],
            ['name' => 'Django', 'ace_mode' => 'django', 'logo' => ''],
            ['name' => 'Dockerfile', 'ace_mode' => 'dockerfile', 'logo' => ''],
            ['name' => 'Dot', 'ace_mode' => 'dot', 'logo' => ''],
            ['name' => 'Drools', 'ace_mode' => 'drools', 'logo' => ''],
            ['name' => 'Edifact', 'ace_mode' => 'edifact', 'logo' => ''],
            ['name' => 'Eiffel', 'ace_mode' => 'eiffel', 'logo' => ''],
            ['name' => 'EJS', 'ace_mode' => 'ejs', 'logo' => ''],
            ['name' => 'Elixir', 'ace_mode' => 'elixir', 'logo' => ''],
            ['name' => 'Elm', 'ace_mode' => 'elm', 'logo' => ''],
            ['name' => 'Erlang', 'ace_mode' => 'erlang', 'logo' => ''],
            ['name' => 'Flix', 'ace_mode' => 'flix', 'logo' => ''],
            ['name' => 'Forth', 'ace_mode' => 'forth', 'logo' => ''],
            ['name' => 'Fortran', 'ace_mode' => 'fortran', 'logo' => ''],
            ['name' => 'FSharp', 'ace_mode' => 'fsharp', 'logo' => ''],
            ['name' => 'FSL', 'ace_mode' => 'fsl', 'logo' => ''],
            ['name' => 'FreeMarker', 'ace_mode' => 'ftl', 'logo' => ''],
            ['name' => 'Gcode', 'ace_mode' => 'gcode', 'logo' => ''],
            ['name' => 'Gherkin', 'ace_mode' => 'gherkin', 'logo' => ''],
            ['name' => 'Gitignore', 'ace_mode' => 'gitignore', 'logo' => ''],
            ['name' => 'Glsl', 'ace_mode' => 'glsl', 'logo' => ''],
            ['name' => 'Gobstones', 'ace_mode' => 'gobstones', 'logo' => ''],
            ['name' => 'Go', 'ace_mode' => 'golang', 'logo' => 'https://img.icons8.com/3d-fluency/50/java-coffee-cup-logo.png'],
            ['name' => 'GraphQLSchema', 'ace_mode' => 'graphqlschema', 'logo' => ''],
            ['name' => 'Groovy', 'ace_mode' => 'groovy', 'logo' => ''],
            ['name' => 'HAML', 'ace_mode' => 'haml', 'logo' => ''],
            ['name' => 'Handlebars', 'ace_mode' => 'handlebars', 'logo' => ''],
            ['name' => 'Haskell', 'ace_mode' => 'haskell', 'logo' => ''],
            ['name' => 'Haskell Cabal', 'ace_mode' => 'haskell_cabal', 'logo' => ''],
            ['name' => 'haXe', 'ace_mode' => 'haxe', 'logo' => ''],
            ['name' => 'Hjson', 'ace_mode' => 'hjson', 'logo' => ''],
            ['name' => 'HTML', 'ace_mode' => 'html', 'logo' => ''],
            ['name' => 'HTML (Elixir)', 'ace_mode' => 'html_elixir', 'logo' => ''],
            ['name' => 'HTML (Ruby)', 'ace_mode' => 'html_ruby', 'logo' => ''],
            ['name' => 'INI', 'ace_mode' => 'ini', 'logo' => ''],
            ['name' => 'Io', 'ace_mode' => 'io', 'logo' => ''],
            ['name' => 'Ion', 'ace_mode' => 'ion', 'logo' => ''],
            ['name' => 'Jack', 'ace_mode' => 'jack', 'logo' => ''],
            ['name' => 'Jade', 'ace_mode' => 'jade', 'logo' => ''],
            ['name' => 'Java', 'ace_mode' => 'java', 'logo' => 'https://img.icons8.com/3d-fluency/50/java-coffee-cup-logo.png'],
            ['name' => 'JavaScript', 'ace_mode' => 'javascript', 'logo' => 'https://img.icons8.com/color/50/javascript--v1.png'],
            ['name' => 'JEXL', 'ace_mode' => 'jexl', 'logo' => ''],
            ['name' => 'JSON', 'ace_mode' => 'json', 'logo' => ''],
            ['name' => 'JSON5', 'ace_mode' => 'json5', 'logo' => ''],
            ['name' => 'JSONiq', 'ace_mode' => 'jsoniq', 'logo' => ''],
            ['name' => 'JSP', 'ace_mode' => 'jsp', 'logo' => ''],
            ['name' => 'JSSM', 'ace_mode' => 'jssm', 'logo' => ''],
            ['name' => 'JSX', 'ace_mode' => 'jsx', 'logo' => ''],
            ['name' => 'Julia', 'ace_mode' => 'julia', 'logo' => ''],
            ['name' => 'Kotlin', 'ace_mode' => 'kotlin', 'logo' => 'https://img.icons8.com/color/50/kotlin.png'],
            ['name' => 'KRL', 'ace_mode' => 'krl', 'logo' => ''],
            ['name' => 'LESS', 'ace_mode' => 'less', 'logo' => ''],
            ['name' => 'LilyPond', 'ace_mode' => 'lilypond', 'logo' => ''],
            ['name' => 'Lisp', 'ace_mode' => 'lisp', 'logo' => ''],
            ['name' => 'LiveCode', 'ace_mode' => 'livecode', 'logo' => ''],
            ['name' => 'Logo', 'ace_mode' => 'logo', 'logo' => ''],
            ['name' => 'Lua', 'ace_mode' => 'lua', 'logo' => ''],
            ['name' => 'Makefile', 'ace_mode' => 'makefile', 'logo' => ''],
            ['name' => 'Markdown', 'ace_mode' => 'markdown', 'logo' => ''],
            ['name' => 'MySQL', 'ace_mode' => 'mysql', 'logo' => ''],
            ['name' => 'MATLAB', 'ace_mode' => 'matlab', 'logo' => ''],
            ['name' => 'MEL', 'ace_mode' => 'mel', 'logo' => ''],
            ['name' => 'MiniD', 'ace_mode' => 'minid', 'logo' => ''],
            ['name' => 'Mirah', 'ace_mode' => 'mirah', 'logo' => ''],
            ['name' => 'ML', 'ace_mode' => 'ml', 'logo' => ''],
            ['name' => 'MQL4', 'ace_mode' => 'mql4', 'logo' => ''],
            ['name' => 'MQL5', 'ace_mode' => 'mql5', 'logo' => ''],
            ['name' => 'NATURAL', 'ace_mode' => 'natural', 'logo' => ''],
            ['name' => '.NET', 'ace_mode' => 'csharp', 'logo' => 'https://img.icons8.com/3d-fluency/50/java-coffee-cup-logo.png'],
            ['name' => 'Nginx', 'ace_mode' => 'nginx', 'logo' => ''],
            ['name' => 'Nim', 'ace_mode' => 'nim', 'logo' => ''],
            ['name' => 'Ninja', 'ace_mode' => 'ninja', 'logo' => ''],
            ['name' => 'Objective C', 'ace_mode' => 'objectivec', 'logo' => ''],
            ['name' => 'OCaml', 'ace_mode' => 'ocaml', 'logo' => ''],
            ['name' => 'Pascal', 'ace_mode' => 'pascal', 'logo' => ''],
            ['name' => 'Perl', 'ace_mode' => 'perl', 'logo' => ''],
            ['name' => 'PHP', 'ace_mode' => 'php', 'logo' => 'https://img.icons8.com/nolan/50/php--v2.png'],
            ['name' => 'Pig', 'ace_mode' => 'pig', 'logo' => ''],
            ['name' => 'Pike', 'ace_mode' => 'pike', 'logo' => ''],
            ['name' => 'PL/SQL', 'ace_mode' => 'plsql', 'logo' => ''],
            ['name' => 'PostScript', 'ace_mode' => 'postscript', 'logo' => ''],
            ['name' => 'PowerShell', 'ace_mode' => 'powershell', 'logo' => ''],
            ['name' => 'Prolog', 'ace_mode' => 'prolog', 'logo' => ''],
            ['name' => 'Puppet', 'ace_mode' => 'puppet', 'logo' => ''],
            ['name' => 'PureScript', 'ace_mode' => 'purescript', 'logo' => ''],
            ['name' => 'Python', 'ace_mode' => 'python', 'logo' => 'https://img.icons8.com/color/50/python--v1.png'],
            ['name' => 'QML', 'ace_mode' => 'qml', 'logo' => ''],
            ['name' => 'R', 'ace_mode' => 'r', 'logo' => ''],
            ['name' => 'Racket', 'ace_mode' => 'racket', 'logo' => ''],
            ['name' => 'Raku', 'ace_mode' => 'raku', 'logo' => ''],
            ['name' => 'Rexx', 'ace_mode' => 'rexx', 'logo' => ''],
            ['name' => 'Robot', 'ace_mode' => 'robot', 'logo' => ''],
            ['name' => 'Ruby', 'ace_mode' => 'ruby', 'logo' => 'https://img.icons8.com/nolan/50/ruby-programming-language.png'],
            ['name' => 'Rust', 'ace_mode' => 'rust', 'logo' => ''],
            ['name' => 'SAS', 'ace_mode' => 'sas', 'logo' => ''],
            ['name' => 'Scala', 'ace_mode' => 'scala', 'logo' => ''],
            ['name' => 'Scheme', 'ace_mode' => 'scheme', 'logo' => ''],
            ['name' => 'SCSS', 'ace_mode' => 'scss', 'logo' => ''],
            ['name' => 'Shell', 'ace_mode' => 'shell', 'logo' => ''],
            ['name' => 'Smalltalk', 'ace_mode' => 'smalltalk', 'logo' => ''],
            ['name' => 'Solidity', 'ace_mode' => 'solidity', 'logo' => ''],
            ['name' => 'SQL', 'ace_mode' => 'sql', 'logo' => ''],
            ['name' => 'Squirrel', 'ace_mode' => 'squirrel', 'logo' => ''],
            ['name' => 'Stylus', 'ace_mode' => 'stylus', 'logo' => ''],
            ['name' => 'Swift', 'ace_mode' => 'swift', 'logo' => 'https://img.icons8.com/color/50/swift.png'],
            ['name' => 'Tcl', 'ace_mode' => 'tcl', 'logo' => ''],
            ['name' => 'Terra', 'ace_mode' => 'terra', 'logo' => ''],
            ['name' => 'Tex', 'ace_mode' => 'tex', 'logo' => ''],
            ['name' => 'Textile', 'ace_mode' => 'textile', 'logo' => ''],
            ['name' => 'TLA', 'ace_mode' => 'tla', 'logo' => ''],
            ['name' => 'TypeScript', 'ace_mode' => 'typescript', 'logo' => 'https://img.icons8.com/fluency/50/typescript--v2.png'],
            ['name' => 'Vala', 'ace_mode' => 'vala', 'logo' => ''],
            ['name' => 'VBScript', 'ace_mode' => 'vbscript', 'logo' => ''],
            ['name' => 'Verilog', 'ace_mode' => 'verilog', 'logo' => ''],
            ['name' => 'VHDL', 'ace_mode' => 'vhdl', 'logo' => ''],
            ['name' => 'Visual FoxPro', 'ace_mode' => 'visualfoxpro', 'logo' => ''],
            ['name' => 'XML', 'ace_mode' => 'xml', 'logo' => ''],
            ['name' => 'XQuery', 'ace_mode' => 'xquery', 'logo' => ''],
            ['name' => 'YAML', 'ace_mode' => 'yaml', 'logo' => ''],
        ]);

        // DB::table('snippet_types')->insert([
        //     ['name' => 'multi']
        // ]);
    }
}
